### ISSUE TITLE
Get Followed Artists

### ISSUE THREAD

**Issue by maracuja-juice** [wittydeveloper/spotify-graphql#69]
In your README you state that you don't support "get followed artists"
But I looked through your schema and it seems like this does the same:
```
me {
  artists {
    name
  }
}
```

Is that correct?

**Comment by wittydeveloper** [comment]
Hello @maracuja-juice,

You are right, this query is definitely available, I've just tested it on the playground: https://spotify-api-graphql-console.herokuapp.com/#_=_

Thanks for noticing,

-----------------------

PS: If you have time, feel free to do a PR to update the doc.
Otherwise, I'll do it later.
